export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#785656",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d4c3c2",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#4a4643",
        "on-tertiary": "#ffffff",
        "surface": "#fbf9f6",
        "secondary-container": "#e6ded7",
        "inverse-surface": "#30312f",
        "tertiary-fixed-dim": "#ccc5c1",
        "secondary-fixed": "#e9e1da",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e8e1dc",
        "on-surface-variant": "#504444",
        "on-secondary-fixed-variant": "#4a4641",
        "surface-bright": "#fbf9f6",
        "inverse-primary": "#e8bcbc",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "background": "#fbf9f6",
        "on-secondary-fixed": "#1e1b17",
        "surface-variant": "#e4e2df",
        "surface-tint": "#785656",
        "on-background": "#1b1c1a",
        "primary-fixed": "#ffdad9",
        "outline": "#827473",
        "on-surface": "#1b1c1a",
        "surface-container-low": "#f5f3f0",
        "secondary": "#625e58",
        "surface-container-highest": "#e4e2df",
        "error-container": "#ffdad6",
        "surface-dim": "#dbdad7",
        "on-tertiary-fixed": "#1e1b18",
        "primary-container": "#b78f8f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#e8bcbc",
        "on-primary-fixed": "#2d1415",
        "surface-container": "#efeeeb",
        "inverse-on-surface": "#f2f0ed",
        "on-tertiary-container": "#34312d",
        "surface-container-high": "#eae8e5",
        "on-secondary-container": "#67625c",
        "on-primary-container": "#45292a",
        "tertiary-container": "#9d9894",
        "on-primary-fixed-variant": "#5e3f3f",
        "tertiary": "#625e5a",
        "secondary-fixed-dim": "#ccc5be"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "stack-lg": "48px",
        "stack-sm": "12px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "stack-md": "24px",
        "container-max": "1140px"
      },
      fontFamily: {
        "label-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "display": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "body-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
}
